### ISSUE TITLE
Configuration not found

### ISSUE THREAD

**Issue by hermann1514** [eXtgmA/ws980wifi#1]
Hi,
i have copied all files to the custom_components folder under ws980wifi.
After i change my config - ha is missing the ws980wifi Component.

Is there something wrong with newer HA Versions?

Can you help?

**Comment by doabigcheese** [comment]
what does the log file saying?

**Comment by hermann1514** [comment]
After i edit the configuration file and check the config, HA display the following:

Platform error sensor.WS980WIFI - Integration 'WS980WIFI' not found.

I have created a directory under custom_components "ws980wifi" and copy all file from your repo to this.

**Comment by hermann1514** [comment]
Here is the complete error:

Platform error sensor.ws980wifi - Integration 'ws980wifi' not found.

**Comment by dancatt** [comment]
same error here

**Comment by patschbo** [comment]
This Issue is fixed with the current version.
