### ISSUE TITLE
Version key needed...

### ISSUE THREAD

**Issue by doabigcheese** [eXtgmA/ws980wifi#2]
https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes/#versions

`2022-06-25 20:51:09 ERROR (SyncWorker_0) [homeassistant.loader] The custom integration 'ws980wifi' does not have a version key in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details`

**Comment by patschbo** [comment]
This Issue is fixed with the current version.
