### ISSUE TITLE
No values display, timed out in logs

### ISSUE THREAD

**Issue by stefandbt** [eXtgmA/ws980wifi#7]
After a fresh HASSIO installation due to a HDD crash, all is configured again and running. Unfortunately the elv_ws980wifi is not providing any values for HASSIO. The software of the weatherstation shows all values as before. Current HASSIO version is Home Assistant 2023.2.1, Supervisor 2023.01.1, Operating System 9.5, Frontend 20230202.0 - latest.

Same error was reported by Crayin (No sensor data with 2021.9.1) in 2021, but this is reported as fixed? What to do?

**Comment by patschbo** [comment]
Did you use the correct IP?
